name: "Update pins for hackage.nix and stackage.nix"

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"

jobs:
  update-pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.zw3rk.com https://cache.nixos.org/
      - name: "Update pins"
        run: |
          nix flake lock --update-input hackage
          nix flake lock --update-input stackage
      - name: Commit and push changes
        run: |
          git config --local user.email "devops+nix-tools@iohk.io"
          git config --local user.name "IOHK"
          git add .
          git commit -m "Update Hackage and Stackage"
          git push